services:
  app:
    build: 
      context: app
    ports:
      - "5055"
    networks:
      - docker_containers_default
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "86:86"

networks:
  docker_containers_default:
    external: true
